import PageHeader from "../components/PageHeader"

function Inversiones() {
  return (
    <>
      <PageHeader titulo="Inversiones"/>
      <section className="padded">
        <div className="container">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi asperiores doloribus inventore assumenda, at corrupti repellat saepe eos, culpa voluptatibus deleniti consequuntur, minus sapiente exercitationem vitae esse expedita nemo! Eveniet nam vel veritatis a voluptatibus. Iusto fugiat dicta ducimus voluptatibus nostrum nobis voluptatem provident similique, molestiae beatae, praesentium neque, sit aspernatur voluptates rem quam non laboriosam nesciunt a nam. Sed nihil quae enim facilis architecto, minima in corporis perspiciatis vitae deleniti ipsum. Temporibus magni asperiores sunt, atque voluptas reprehenderit minus deserunt qui necessitatibus et. Voluptate atque officiis molestias soluta dolorum! Earum sed, provident tempore explicabo dolorem exercitationem incidunt doloremque facilis dignissimos labore! Pariatur, nobis. Nostrum distinctio incidunt reprehenderit, maiores, esse quis voluptatibus praesentium nulla molestiae perspiciatis dolorum sed molestias fugit.</p>
          <p>Autem, blanditiis natus. Facilis esse delectus labore, soluta excepturi assumenda hic voluptas fugit ad, doloremque debitis recusandae dolore quisquam inventore, dolores saepe nobis. In facilis blanditiis placeat id consectetur, impedit deleniti tempora eaque cumque illum esse vitae ratione architecto dolor iste dolorem quibusdam dolore non, ullam, illo accusamus eligendi ipsum! Vero quod consequuntur iste, error pariatur alias illo doloremque officiis voluptate in nobis, ab impedit commodi eveniet maiores. Provident obcaecati doloribus hic, saepe tenetur et consequuntur eaque eius cum quam amet dicta? Nesciunt quia sapiente rem dignissimos unde. Iusto sed inventore perferendis doloribus, molestiae minus dolorem sequi ratione quibusdam ducimus recusandae nostrum corrupti possimus error quia non suscipit, esse sapiente libero nesciunt veritatis et? Suscipit blanditiis enim voluptas harum vero.</p>
          <p>Numquam facilis velit reiciendis dolorum fugiat quia tempora accusamus, ullam odio ab, possimus sint deserunt laboriosam molestias inventore voluptas pariatur ratione consequuntur impedit autem! Quidem aperiam nam praesentium sint dolores hic asperiores nostrum! Deserunt distinctio voluptatem necessitatibus nihil, accusantium, ad a sunt, nisi pariatur quas totam quaerat deleniti. Sint animi aspernatur cumque maxime rerum aliquid autem, quo sequi provident dolorem accusamus ullam consequatur placeat at eum amet minima quae praesentium commodi! Beatae modi quisquam ducimus pariatur aperiam, consectetur, quia vitae repudiandae a hic officia corporis deleniti autem nulla, ex excepturi praesentium iste soluta animi laboriosam dicta in nihil! Qui aperiam saepe impedit minus veniam ipsam adipisci ipsa, assumenda ex facere doloremque, vitae facilis ducimus non ullam nesciunt est cumque maxime.</p>
          <p>Cum ratione nobis rerum ullam omnis. Dolorum adipisci voluptates officiis id laudantium labore doloribus modi enim voluptatum exercitationem, cum esse aspernatur! Libero nostrum odit doloribus quis autem, quidem quod impedit iure ipsam excepturi sit dicta eum provident officiis! Iusto consectetur autem, nisi ipsa impedit accusantium quae voluptatum enim incidunt labore itaque blanditiis sunt perspiciatis voluptates, consequatur magni. Molestias suscipit provident facilis tenetur officiis maxime asperiores excepturi quibusdam ratione ullam magnam fugit possimus accusamus fuga dicta perspiciatis soluta, autem totam quam facere ad. Nobis minima architecto quia, nam optio dignissimos eaque ad cumque omnis autem doloribus laboriosam ea blanditiis expedita illo iure amet assumenda molestiae, eligendi delectus, sapiente velit sint. Obcaecati officia nobis autem. Unde facere repudiandae ipsa sequi blanditiis cupiditate?</p>
          <p>Ullam ab officia illum cupiditate placeat ducimus delectus necessitatibus, eius ipsa praesentium fugiat consectetur inventore quis similique et quia qui molestias reiciendis distinctio natus. Doloremque animi quis quod distinctio nostrum necessitatibus perspiciatis. Atque deserunt totam excepturi enim voluptatum minima explicabo aliquam, aperiam officiis ipsum officia velit placeat animi, ullam inventore nemo dolorum. Laborum dolorum nemo asperiores ipsam, aperiam quidem laudantium sunt porro praesentium unde necessitatibus dignissimos voluptatem rem, consequatur quia impedit vero aliquam perspiciatis modi at inventore! Suscipit fugit voluptas delectus totam nulla soluta cupiditate voluptatum recusandae eligendi porro ducimus exercitationem obcaecati, nostrum maxime. Numquam, ex et. Est voluptate ipsum culpa adipisci voluptatibus doloremque iure sequi facere qui! Quaerat odit aliquid optio nihil in beatae maxime repellat tempore consequuntur facere.</p>
        </div>
      </section>
    </>
  )
}

export default Inversiones